# Eduard Schornig (eschorni@cisco.com) | version 0.3

#  Copyright (c) 2020 Cisco and/or its affiliates.
#  This software is licensed to you under the terms of the Cisco Sample
#  Code License, Version 1.1 (the "License"). You may obtain a copy of the
#  License at
#  https://developer.cisco.com/docs/licenses
#  All use of the material herein must be in accordance with the terms of
#  the License. All rights not expressly granted by pytthe License are
#  reserved. Unless required by applicable law or agreed to separately in
#  writing, software distributed under the License is distributed on an "AS
#  IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  or implied.

version: "3"
services:
  grafana:
    container_name: grafana-ui
    restart: always
    image: grafana/grafana
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    user: "0"
    networks:
      - webnet
    environment:
      - "TZ=Europe/Amsterdam"
      - "GF_INSTALL_PLUGINS=natel-discrete-panel"
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/config.ini:/etc/grafana/config.ini"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
  influxdb:
    container_name: influxdb-datasource
    restart: always
    image: influxdb
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - "./influxdb:/var/lib/influxdb"
    environment:
      - "TZ=Europe/Amsterdam"
    networks:
      - webnet
  collector:
    container_name: stats-collector
    restart: always
    build:
      context: stats-collector-docker
    deploy:
      restart_policy:
        condition: on-failure
    command: python3 /usr/src/app/viptela-collector.py
    volumes:
      - "./stats-collector-code:/usr/src/app"
    environment:
      - "TZ=Europe/Amsterdam"
    networks:
      - webnet
networks:
  webnet:
